package com.abelhzo.security.entities;
// Generated 30 jun. 2023 17:01:16 by Hibernate Tools 6.2.4.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "ROLES", schema = "PUBLIC", catalog = "SECUREDB", uniqueConstraints = @UniqueConstraint(columnNames = "ROL"))
public class Rol implements java.io.Serializable {

	private static final long serialVersionUID = 2714693151530435832L;
	private Integer idRol;
	private String rol;

	public Rol() {
	}

	public Rol(String rol) {
		this.rol = rol;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_ROL", unique = true, nullable = false)
	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	@Column(name = "ROL", unique = true, nullable = false, length = 50)
	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

}
