package com.abelhzo.security.entities;
// Generated 30 jun. 2023 17:01:16 by Hibernate Tools 6.2.4.Final

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "USERS", schema = "PUBLIC", catalog = "SECUREDB", uniqueConstraints = @UniqueConstraint(columnNames = "USERNAME"))
public class User implements java.io.Serializable {

	private static final long serialVersionUID = -5106929169228148874L;
	private Long idUser;
	private String username;
	private String password;
	private Date birthday;
	private byte[] photo;
	private Timestamp creationDate;
	private Set<UserRol> userRols = new HashSet<UserRol>(0);

	public User() {
	}

	public User(Long idUser, String username, String password, Date birthday, byte[] photo, Timestamp creationDate,
			Set<UserRol> userRols) {
		this.idUser = idUser;
		this.username = username;
		this.password = password;
		this.birthday = birthday;
		this.photo = photo;
		this.creationDate = creationDate;
		this.userRols = userRols;
	}

	@Id
	@Column(name = "ID_USER", unique = true, nullable = false)
	public Long getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Long idUser) {
		this.idUser = idUser;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 80)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 80)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BIRTHDAY", nullable = false, length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "PHOTO")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATION_DATE", nullable = false, length = 26)
	public Timestamp getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Timestamp creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user", cascade = CascadeType.ALL)
	public Set<UserRol> getUserRols() {
		return this.userRols;
	}

	public void setUserRols(Set<UserRol> userRols) {
		this.userRols = userRols;
	}

}
